### ISSUE TITLE
Count main-foto-matches

### ISSUE THREAD

**Issue by TassiloKubitz** [danielsu/GoogleContributionStatsGrabber#2]
if the foto is the current main foto of the location, there is a match. All other ranks are not match.

- The sum of matches should be displayed at top. 
- Each line of stats should show the match true or false

**Comment by danielsu** [comment]
check out release v 0.1.1 for main photo matching and highlighting. Count of matches may follow later.

**Comment by danielsu** [comment]
done with v0.2.0
